### ISSUE TITLE
consider peterh/liner for completion+pager

### ISSUE THREAD

**Issue by sbinet** [abiosoft/ishell#1]
hi,

I have also been working on a package to implement interactive shells, like python's `cmd` module:
 https://github.com/go-hep/pawgo/blob/master/cmd.go
(I haven't extracted it yet from this pawgo command...)

I'd recommand the `github.com/peterh/liner` package for completion, history and terminal handling.

**Comment by abiosoft** [comment]
Checking it out right away.

Thanks a bunch.

**Comment by abiosoft** [comment]
I have implemented it using https://github.com/chzyer/readline.

Thanks for your suggestion.
