### ISSUE TITLE
Custom contextual completers for commands

### ISSUE THREAD

**Issue by Inphi** [abiosoft/ishell#10]
Can ishell allow users to hook into the PrefixCompleterInterface when we Register commands? I'd like to be able to provide autocompletion given a command currently in the read line.
For example:

> $ login --
> --timeout --user --password

Furthermore, the autocompletion should be dynamic (which is probably possible via readline.PcItemDynamic):

> $ ls /
> bin tmp sbin etc

**Comment by evilfrog** [comment]
+1

**Comment by abiosoft** [comment]
Just a bit of status update.

Right now there is https://godoc.org/github.com/abiosoft/ishell#Shell.CustomCompleter. But that is a bit too difficult for the average person to implement. 

I'm working on something much simpler. If I couldn't get desired result, we may have to make do with above. But I'm optimistic.

**Comment by abiosoft** [comment]
Done. Use `Cmd.Completer` https://godoc.org/github.com/abiosoft/ishell#Cmd.

**Comment by jialeicui** [comment]
@abiosoft 
should `getWords` append  `cmd.children` even if `Completer` is set?
