### ISSUE TITLE
How to build this project

### ISSUE THREAD

**Issue by blinkok** [abiosoft/ishell#115]
Sorry for posting this here and my ignorance but i'd like to know how to build this product or if it requires some other product in order to run.
Again please forgive my ignorance and thanks you very much for any insight you can provide
I am looking at a windows target platform

**Comment by tomruk** [comment]
You don't have to build ishell, it is not a product, it is an open source library. Just type `go get -v github.com/abiosoft/ishell` into your terminal and use it in your project.

**Comment by blinkok** [comment]
Thanks. When you say "Terminal", What terminal are you referring to?

**Comment by tomruk** [comment]
Sorry for late reply, terminal is a program that takes an input from you and processes that input. In windows it is Command Prompt (also known as), in macOS it is Terminal, in Linux it is gnome-terminal (mostly)

In order to build and use the ishell you should know how to use a terminal.

**Comment by blinkok** [comment]
Ok. Thank you very much

**Comment by abiosoft** [comment]
@blinkok Looks like you're new to Go and/or programming. You may want to start from here https://golang.org/doc/install.

**Comment by blinkok** [comment]
Yes. New to go/ishell. Are there any other dependencies?

**Comment by blinkok** [comment]
When i try to execute go get -v github.com/abiosoft/ishell
It gives me an error
**C:\Users\tony\hello>go get -v github.com/abiosoft/ishell
github.com/abiosoft/ishell (download)
go: missing Git command. See https://golang.org/s/gogetcmd
package github.com/abiosoft/ishell: exec: "git": executable file not found in %PATH%**
