### ISSUE TITLE
Ability to pass in extra arguments to commands is gone

### ISSUE THREAD

**Issue by Herkemer** [abiosoft/ishell#14]
In v1 you were able to do something like this:

shell := ishell.New()
myObj := somelib.New(arg arg arg)

shell.Register("blah", blahfunc(shell, myObj))

Then blahfunc could do all sorts of things with myObj.

Am I missing how you can do this with the v2 API?

**Comment by abiosoft** [comment]
Are you talking about command args available via `Context.Args` https://godoc.org/github.com/abiosoft/ishell#Context ?

**Comment by Herkemer** [comment]
Not exactly, I'm talking about passing in additional args at function create time.  However, I might see how to do it, let me poke at it today and I'll come back with either more info or to close this if I figure it out.

**Comment by abiosoft** [comment]
you can always do something like
```
func shellFunc(myargs) func(c *ishell.Context) {
  return func(c *ishell.Context){
    // do something with myargs     
  }
}
```

**Comment by abiosoft** [comment]
I will reopen this when we are able to ascertain that this is indeed an issue.
