### ISSUE TITLE
Exit current command, not the whole shell

### ISSUE THREAD

**Issue by NeutronStein** [abiosoft/ishell#16]
Add possibility to exist current command (c.Stop) without exiting the whole shell(current behaviour).

**Comment by abiosoft** [comment]
I think returning anywhere in the command function gives same behaviour.
```go
func (c *ishell.Context) {
  if someCondition {
    return
  }
  // do something else
}
```

**Comment by NeutronStein** [comment]
In fact, I was trying to stop command whitin a goroutine. context.Stop() stops the whole shell.
Example:
```go
...
func (c *ishell.Context) {
  go myfunc(c, mydata)
}
...
func myfunc(c *ishell.Context, mydata data) {
  if someCondition {
    c.Stop()
    return
  }
  ...
}

```

**Comment by abiosoft** [comment]
You should use channels if that is your use case. And you should structure the code in a way that you can terminate it and not have an isolated goroutine. i.e. `myfunc(c, mydata)` should be stoppable.

If you give a clearer example of what you want to achieve (or show contents of `myfunc`), I am willing to help with a snippet.
