### ISSUE TITLE
doubled output with Context.Printf()

### ISSUE THREAD

**Issue by mmp** [abiosoft/ishell#17]
The attached program creates two commands; the first, "foo", uses ishell.Context.Println() to print "foo', and the second, "bar" uses ishell.Context.Printf() to print "bar". If I build it and run it (on OSX, FWIW), giving it the command "foo", gives me one "foo" printed, but multiple "bar"s are printed for the "bar" command. (Note that the output looks like I entered "bar" multiple times, but I actually only entered it once.)

```
go build . && ./bug
>>> foo
foo
>>> bar
bar
>>> bar
>>> bar
^D
EOF
```

Looking at actions.go, I notice that Println() only sends output to s.writer, but that Print() and Printf() send output to both that and s.reader.buf. I haven't dug further to understand why this is.

[bug.go.txt](https://github.com/abiosoft/ishell/files/762631/bug.go.txt)

**Comment by abiosoft** [comment]
@mmp can you confirm if this has been fixed ?

**Comment by mmp** [comment]
Confirmed--thanks!

(And thanks for writing ishell; it's a delight!)
