### ISSUE TITLE
command arg validation

### ISSUE THREAD

**Issue by sherzberg** [abiosoft/ishell#2]
Any thoughts on having argument validation and/or help strings per command?

I'd like to have some kind of validation built in where I can specify that a command takes in specific args and have ishell be able to process the arguments and report any errors.

**Comment by sherzberg** [comment]
Sub commands would also be awesome. This could help with autocompletion.

**Comment by abiosoft** [comment]
This would be nice to have. I'd look into it.

**Comment by FlorianOtel** [comment]
+1 on subcommands. 

Any progress with that ?

**Comment by abiosoft** [comment]
I will soon start working on subcommands and I've added it to the roadmap. https://github.com/abiosoft/ishell#roadmap-in-no-particular-order.

**Comment by dotslash** [comment]
Hey @abiosoft 
I have a feature request which is very related to this. I want to distinguish between number arguments and string arguments

Example  
```>>> command_name "0" 1 "arg2" arg3```
I want to know that 
arg[0] is a string with value "0"
arg[1] is a number (int/long)
arg[2], arg[3] are strings


Any plans on supporting this?

**Comment by abiosoft** [comment]
@sherzberg Check out the current master for an implementation of subcommands. 
Though it contain breaking changes and you will need to update your codes. The previous version is still available on gopkg.in/abiosoft/ishell.v1.

**Comment by abiosoft** [comment]
@dotslash I'm not sure I'll be implementing your request as you can easily parse the string from the command arguments.

**Comment by abiosoft** [comment]
The new subcommand feature handles this.

Thanks.
