### ISSUE TITLE
Feature: integration with spinner and progress bar libraries

### ISSUE THREAD

**Issue by synw** [abiosoft/ishell#20]
I tried without success to use some library for spinners ( github.com/briandowns/spinner ) but it seems that the shell is taking over the display.

This is a feature request: compatibility with some spinners and progress bar libraries, or core integration of the feature. 

I would use the spinner for waiting until timeouts, and the progress bar to display some incoming time info about an operation in progress.

Thanks for your library anyway

**Comment by abiosoft** [comment]
I have this in mind actually, not just sure of which library to use yet. I'll add it to the roadmap.

**Comment by abiosoft** [comment]
FYI I tried out github.com/briandowns/spanner and it works perfectly. So it gets my vote and I'll be integrating it.

**Comment by abiosoft** [comment]
Done https://github.com/abiosoft/ishell#progress-bar
