### ISSUE TITLE
Access to interruptCount

### ISSUE THREAD

**Issue by Herkemer** [abiosoft/ishell#21]
Perhaps there is a better way to do this but it's currently escaping me so any advice is appreciated.

I'm writing a custom interrupt handler but I'd like to make use of interruptCount similar to the way the default handler function works.  But I don't believe I have access to that interruptCount variable to check or increment.

Perhaps making that variable public or giving access to it in some other way?

Alternatively, giving a hook where the count can be reset would work as well.

Again, if I'm missing something then I'd appreciate a point in the right direction.

Thanks!

**Comment by abiosoft** [comment]
There you have it. https://godoc.org/github.com/abiosoft/ishell#Shell.Interrupt

**Comment by abiosoft** [comment]
Though that is a breaking change. I implemented immediately as I can see the relevance.

Plus, v2 is not final yet.

**Comment by Herkemer** [comment]
Thanks! exactly what I needed.
