### ISSUE TITLE
Add graceful processing for non-latin symbols: Error: Unknown rune: 1087

### ISSUE THREAD

**Issue by pavel-odintsov** [abiosoft/ishell#22]
Hello!

Thank you for your awesome library!  I'm using it for CLI management.

I recently discovered that ishell fails when I enter some non-latin letters, for example "привет" accidentally.

And ishell stopping immediately:
```
root@cli> привет
Error: Unknown rune: 1087

<application stopped>
```

Could you add graceful processing for this case and just return error "incorrect rune" to CLL shell without stopping ishell application?

Thank you for your attention!

**Comment by abiosoft** [comment]
What version of ishell are you using ?

**Comment by abiosoft** [comment]
The behaviour I'm getting is different. Yes, there is an error message but the application is not getting terminated.
```
❯ go run example/main.go
Sample Interactive Shell
>>> привет
Error: Unknown rune: 1087
>>> |
```

**Comment by pavel-odintsov** [comment]
This one: fb8c158a6681dcda157e2bdbe8fe7b0b419c7cbb

**Comment by pavel-odintsov** [comment]
Oh, that's awesome! I will rebase to this branch and check! Thank you!

**Comment by abiosoft** [comment]
There are differences between v1 and v2 (current master). You will have to do couple of refactors to make your app compatible.

**Comment by abiosoft** [comment]
You can re-open this if the issue still exists.

**Comment by abiosoft** [comment]
Also, you can put the characters in quotes as a workaround.
```
❯ go run example/main.go
Sample Interactive Shell
>>> greet "привет"
Hello привет
>>>
```

**Comment by fyrchik** [comment]
Hello! Is there any plan to fix this? I can do this if it doesn't require a lot of refactoring and won't break something.
While commands can be latin-only it is quite common to use unicode in filenames or command arguments.

**Comment by fyrchik** [comment]
@abiosoft what do you think about providing custom splitter in config (defaulting to current `shlex.Split`)?
I can make a PR. Seems like the least invasive option.

**Comment by fy0** [comment]
go-shlex caused it:
```
	cmd := "D:\\codes\\测试\\aaaa.exe asdasd"
	fmt.Println(shlex.Split((cmd)))
```
