### ISSUE TITLE
adding RawArgs on Context

### ISSUE THREAD

**Issue by pierrec** [abiosoft/ishell#25]
Hello,

As I am using ishell in a mix environment where I need to process shell commands as well as non shell commands that need to be sent elsewhere, I would like to discuss the feasibility to add a way to access the unprocessed set of strings (RawArgs) as opposed to the shell processed ones (removal of quotes and escaped characters handling). This would be especially useful when dealing with NotFound commands in which case you could just delegate the parsing to another handler.

What do you think?

**Comment by abiosoft** [comment]
That makes sense. It can be an additional variable to the context.

**Comment by abiosoft** [comment]
Implemented
