### ISSUE TITLE
Possibility to have one-off execution of commands

### ISSUE THREAD

**Issue by mindreframer** [abiosoft/ishell#28]
Hey Abiola, 

first: awesome library! Really-really enjoying it. The amount of functionality I get from just including it is staggering. Autocomplete, shell history, password masking, process bars, multiline input, paged output... Wow. Wow. Wow. So useful. Especially in devops context. Thank you for this package! 

What I was thinking: how hard would it be to also allow non-interactive use? Just parsing args, executing that one single command and then exit? It would be very useful in scripted environments, like CI and such. 

What are your thoughts on this? 

Best, 
Roman

**Comment by abiosoft** [comment]
Thanks for your kind words :)

Can you explain a bit more about how that is expected to work and the usecases. 

If I get you right, instead of getting into interactive mode, just execute the command and exit.

**Comment by abiosoft** [comment]
I think I get you now. Basically ishell without the interactiveness. 

That sure can be done. I'm just thinking there are better libraries out there doing this already. e.g. spf13/cobra.

But I like the idea of toggling interactive and non-interactive mode with same code base.

**Comment by mindreframer** [comment]
Yes, targeting different use cases with the same code base. I understand that this would be probably not that trivial - if we would add proper flag parsing and such... But we could start with the low hanging fruit: same command as in the interactive mode, just non-interactively executed. That alone would help a lot. All other bells & whistles might be non required. Just to keep the surface of this feature as small as possible. 

If you think I could help somehow, just ask me. Glad to be lend a hand on this :)

**Comment by abiosoft** [comment]
This is a start https://godoc.org/github.com/abiosoft/ishell#Shell.Process.

e.g. `shell.Process(os.Args[1:])`

**Comment by abiosoft** [comment]
I think it's safe to close this as the feature has been added.

Processing flags e.t.c are extra features and this thread can still be used for that discussion.

**Comment by mindreframer** [comment]
😻  @abiosoft It's awesome, thank you! This is exactly what I wanted!  I will make a pull request with a Readme update later.
