### ISSUE TITLE
History

### ISSUE THREAD

**Issue by sherzberg** [abiosoft/ishell#3]
Have you thought about how you want command history to work? If you have some ideas on architecture for this, I'd love to help out.

**Comment by abiosoft** [comment]
For history to work, the ability to dynamically change user input at prompts is required. I have not given it a full thought yet, work got a hold of me so I have not had time for a while :(.

I'd love to hear your thoughts.

Thanks.

**Comment by dokipen** [comment]
I think it would be futile to not just integrate readline (unless you have some licencing problams with rl). In the meantime, this works nicely. https://github.com/hanslub42/rlwrap

**Comment by abiosoft** [comment]
This has been implemented. Thanks for your contributions @dokipen.

**Comment by dokipen** [comment]
Just curious, why'd you decide on gopkg.in/readline.v1?

**Comment by abiosoft** [comment]
Its same package as `github.com/chzyer/readline`, just a versioned one. You can check out http://gopkg.in for more.

**Comment by dokipen** [comment]
Ah, I see! Neat. Thanks for implementing. In production now.
