### ISSUE TITLE
Checklist and MultiChoice have undesired behaviour when the term.height<len(options)

### ISSUE THREAD

**Issue by ahmetb** [abiosoft/ishell#35]
**Firstly**, if the list of `options` to `Checklist()` are greater than the row count of the terminal, **the end of list is shown, even though the cursor is at the beginning**

List of options: https://gist.github.com/ahmetb/f73482d3f11c0b5cdc4af1daf3cdbefd

![image](https://user-images.githubusercontent.com/159209/27051583-70c31d1a-4f6b-11e7-8189-12554d4960c4.png)

You can see that this is the end of my `options`.

If I hit UpArrow key to go back to the end of list, it successfully does:

![image](https://user-images.githubusercontent.com/159209/27051609-8bd13cfe-4f6b-11e7-8b98-2b64c0381aa5.png)

**Secondly**, if the term.height is a lot less than list of options, using Up/Arrow down keys do not update screen to always show the ❯ cursor. Inquisitor.js can be a good example of how this can be performed correctly.

I can still move the cursor to point to another option, but I can't see the item I am pointing at once it's off-screen.

**Comment by chessman** [comment]
@abiosoft I can try to fix it because it affects me too. Any ideas how to implement pagination in terminal? It looks that it is easy to find out terminal size. But Checklist can be printed not from the beginning of the screen. I need to know height of Checklist area.

**Comment by abiosoft** [comment]
We can handle the condition for term.height < len(options) separately and intelligently print only what the user expects to see.

**Comment by ahmetb** [comment]
@chessman I strongly recommend Inquisitior.js. It's been out there for at least 4 years.

**Comment by chessman** [comment]
@ahmetb Do you suggest this project? https://github.com/dailymuse/inquisitor.js
I can't find any CLI-related code here.

**Comment by ahmetb** [comment]
@chessman my bad. https://github.com/SBoudrias/Inquirer.js/

**Comment by chessman** [comment]
@ahmetb Nice project. They fix number of items per page, it didn't occur to me. I scroll screen to be on the top to free maximum space. It can be avoided. If I had enough time I would implement it as in Inquirer.js.

**Comment by ahmetb** [comment]
Thanks, it works good enough for now.
