### ISSUE TITLE
Checklist() does not scroll among the options if the term.height<len(options)

### ISSUE THREAD

**Issue by ahmetb** [abiosoft/ishell#36]
Similar to #35, if the term.height is a lot less than list of options, using Up/Arrow down keys do not update screen to always show the `❯` cursor. Inquisitor.js can be a good example of how this can be performed correctly.

I can still move the cursor to point to another option, but I can't see the item I am pointing at once it's off-screen.

**Comment by abiosoft** [comment]
This should be merged with #35
