### ISSUE TITLE
Checklist() and MultiChoice() are indistinguishable in the runtime for end-users

### ISSUE THREAD

**Issue by ahmetb** [abiosoft/ishell#40]
Currently users have no visual way of telling between Checklist() and MultiChoice(). It's not clear whether they can pick one or multiple items. 

Inquirer.js uses some unicode characters to indicate that it is a checklist.

![](https://github.com/SBoudrias/Inquirer.js/raw/master/assets/screenshots/checkbox-prompt.png)

For a plain multi-choice list, it uses what ishell uses now:

![](https://github.com/SBoudrias/Inquirer.js/raw/master/assets/screenshots/list-prompt.png)

**Comment by abiosoft** [comment]
The ideal scenario would be to make it configurable. So, irrespective of what symbols are used, users can override it if desired.

**Comment by abiosoft** [comment]
Changed to this.

<img width="386" alt="screen shot 2017-06-16 at 6 52 44 pm" src="https://user-images.githubusercontent.com/240448/27238495-0b3a54ba-52c5-11e7-95b9-c384c4db7499.png">

**Comment by ahmetb** [comment]
Wonderful thank you. There might be concerns regarding these characters someday if you decide to support Windows. Inquirer.js has platform-specific character choices.
