### ISSUE TITLE
readline.ClearScreen only returns error vs (int, error) on Windows

### ISSUE THREAD

**Issue by bennettaur** [abiosoft/ishell#43]
Looking at readline, it likes like the code for Windows for the call to ClearScreen only returns 1 arg rather than 2 for Unix, causing ishell to not compile on windows because of:
https://github.com/abiosoft/ishell/blob/master/actions.go#L167

Readline Windows:
https://github.com/chzyer/readline/blob/283f5429f7723ac628cb68a44a11097c11a7a9c1/utils_windows.go#L31

Unix:
https://github.com/chzyer/readline/blob/8a1389155f133761e8e73b585f47ed27a78b74d5/utils_unix.go#L48

**Comment by abiosoft** [comment]
Wow, I didn't notice this. Do you mind sending in a fix for this ?

**Comment by bennettaur** [comment]
I made a quick fix https://github.com/abiosoft/ishell/pull/44 but if you have a different opinion on design, I'm open to it.
