### ISSUE TITLE
How to clear prompt on same line?

### ISSUE THREAD

**Issue by omani** [abiosoft/ishell#49]
Hi all,

first of all great piece of software. really like it.

I would like to know if there is an option equivalent to ClearScreen() but one which only clears the actual line instead of the whole screen.

so for example:
```
>>> something written on this line
```

and when I hit CTRL + C (which I can catch with Interrupt()) I want the line to be empty on the same line:
```
>>> 
```

without moving into a new prompt line.

is this possible?

**Comment by abiosoft** [comment]
Not yet.
But there can be an intelligent workaround by clearing previous lines.

I'm trying out something, if it works I'll share it here or maybe add it to the library.

**Comment by abiosoft** [comment]
Pull the latest, I have modified the interrupt handler function to pass in the line as well.

This works on unix. Should work on Windows but I'm not sure.
```go
shell.Interrupt(func(c *ishell.Context, count int, line string) {
	lineCount := len(strings.Split(line, "\n"))
	c.Printf("\033[%dA", lineCount+1)
	c.Println()
})
```
