### ISSUE TITLE
The example doesn't work.

### ISSUE THREAD

**Issue by kubawi** [abiosoft/ishell#57]
file: 'file:///c%3A/Users/wiecbuk/go/src/stash.dts.fm.rbsgrp.net/ep/edt_command_client.git/spike.go'
severity: 'Error'
message: 'unknown field 'Aliases' in struct literal of type ishell.Cmd'
at: '44,3'
source: ''

file: 'file:///c%3A/Users/wiecbuk/go/src/stash.dts.fm.rbsgrp.net/ep/edt_command_client.git/spike.go'
severity: 'Error'
message: 'c.MultiChoice undefined (type *ishell.Context has no field or method MultiChoice)'
at: '72,4'
source: ''

file: 'file:///c%3A/Users/wiecbuk/go/src/stash.dts.fm.rbsgrp.net/ep/edt_command_client.git/spike.go'
severity: 'Error'
message: 'c.Checklist undefined (type *ishell.Context has no field or method Checklist)'
at: '92,4'
source: ''

file: 'file:///c%3A/Users/wiecbuk/go/src/stash.dts.fm.rbsgrp.net/ep/edt_command_client.git/spike.go'
severity: 'Error'
message: 'shell.Process undefined (type *ishell.Shell has no field or method Process)'
at: '193,3'
source: ''

file: 'file:///c%3A/Users/wiecbuk/go/src/stash.dts.fm.rbsgrp.net/ep/edt_command_client.git/spike.go'
severity: 'Error'
message: 'shell.Run undefined (type *ishell.Shell has no field or method Run)'
at: '196,3'
source: ''

file: 'file:///c%3A/Users/wiecbuk/go/src/stash.dts.fm.rbsgrp.net/ep/edt_command_client.git/spike.go'
severity: 'Error'
message: 'shell.Close undefined (type *ishell.Shell has no field or method Close)'
at: '198,3'
source: ''

**Comment by abiosoft** [comment]
Looks like you have an older version of the library in your `GOPATH` and a more recent example.

Run `go get -u github.com/abiosoft/ishell`.
