### ISSUE TITLE
Feature request: make context values public available

### ISSUE THREAD

**Issue by omani** [abiosoft/ishell#60]
hi,

it would be a benefit to have:
```
// Context is an ishell context. It embeds ishell.Actions.
type Context struct {
	values      map[string]interface{}
```

```values``` exposed so one can iterate through the keys and values.

because right now when passing contexts from method to method with keys set by c.Set() the target method needs to know which key was meant so it can operate on it.

**Comment by omani** [comment]
of course it doesn't have to be exposed. a ```Context``` method returning the whole map would work, too.

**Comment by abiosoft** [comment]
How about a `Keys() []string` method ?

**Comment by omani** [comment]
yes, that would be enough.

**Comment by abiosoft** [comment]
Wow, I thought I have fixed this.

Fixed now.
