### ISSUE TITLE
invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by dr1ss** [abiosoft/ishell#64]
Hello guys,
tryed the main.go in the examples folder, seems like there is a problem with the readPassword() on go version go1.9.1 darwin/amd64 (mac) 

`panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x1206f61]

goroutine 1 [running]:
github.com/chzyer/readline.(*RuneBuffer).output(0xc42008c8c0, 0x0, 0xc420051838, 0x120817c)
        /Users/xxxx/Go/src/github.com/chzyer/readline/runebuf.go:494 +0xd1
github.com/chzyer/readline.(*RuneBuffer).print(0xc42008c8c0)
        /Users/xxxx/Go/src/github.com/chzyer/readline/runebuf.go:475 +0x2b
github.com/chzyer/readline.(*RuneBuffer).Refresh(0xc42008c8c0, 0x0)
        /Users/xxxx/Go/src/github.com/chzyer/readline/runebuf.go:465 +0xb2
github.com/chzyer/readline.(*Operation).Runes(0xc4200fe000, 0x0, 0x0, 0x0, 0x0, 0x0)
        /Users/xxxx/Go/src/github.com/chzyer/readline/operation.go:388 +0xf9
github.com/chzyer/readline.(*Operation).Slice(0xc4200fe000, 0x12c1710, 0xc420010b50, 0x0, 0x107be01, 0xc420166d80)
        /Users/xxxx/Go/src/github.com/chzyer/readline/operation.go:429 +0x2f
github.com/chzyer/readline.(*Operation).PasswordWithConfig(0xc4200fe000, 0xc420166d80, 0x0, 0x0, 0x0, 0x0, 0x0)
        /Users/xxxx/Go/src/github.com/chzyer/readline/operation.go:417 +0xb5
github.com/chzyer/readline.(*Operation).PasswordEx(0xc4200fe000, 0xc420160166, 0xa, 0x0, 0x0, 0x0, 0xc420051b48, 0xc42011c000, 0x16006c8, 0x0)
        /Users/xxxx/Go/src/github.com/chzyer/readline/operation.go:405 +0x165
github.com/chzyer/readline.(*Operation).Password(0xc4200fe000, 0xc420160166, 0xa, 0x1045db9, 0xc420160166, 0xc42013e028, 0xa, 0xc420160166)
        /Users/xxxx/Go/src/github.com/chzyer/readline/operation.go:421 +0x55
github.com/chzyer/readline.(*Instance).ReadPassword(0xc42012c000, 0xc420160166, 0xa, 0x40, 0xc420160166, 0xa, 0x20, 0xa)
        /Users/xxxx/Go/src/github.com/chzyer/readline/readline.go:232 +0x43
github.com/abiosoft/ishell.(*shellReader).readPasswordErr(0xc420134060, 0x1210932, 0x13eb220, 0xc42000e018, 0xc42016a160)
        /Users/xxxx/Go/src/github.com/abiosoft/ishell/reader.go:49 +0xd5
github.com/abiosoft/ishell.(*shellReader).readPassword(0xc420134060, 0x0, 0x0)
        /Users/xxxx/Go/src/github.com/abiosoft/ishell/reader.go:54 +0x2b
github.com/abiosoft/ishell.(*shellActionsImpl).ReadPassword(0xc420140000, 0xc42016a160, 0x1)
        /Users/xxxx/Go/src/github.com/abiosoft/ishell/actions.go:81 +0x32
main.main.func1(0xc42018a000)
        /Volumes/Secondary/Boulot/Experiments/go/genious/gcreport/gcreport.go:63 +0x24f
github.com/abiosoft/ishell.(*Shell).handleCommand(0xc420132000, 0xc42016a0a0, 0x1, 0x1, 0x1213c96, 0xc420051de8, 0xc420051dd8)
        /Users/xxxx/Go/src/github.com/abiosoft/ishell/ishell.go:248 +0x2fc
github.com/abiosoft/ishell.handleInput(0xc420132000, 0xc42016a0a0, 0x1, 0x1, 0xc420132000, 0xc420156060)
        /Users/xxxx/Go/src/github.com/abiosoft/ishell/ishell.go:202 +0x4d
github.com/abiosoft/ishell.(*Shell).run(0xc420132000)
        /Users/xxxx/Go/src/github.com/abiosoft/ishell/ishell.go:181 +0x245
github.com/abiosoft/ishell.(*Shell).Run(0xc420132000)
        /Users/xxxx/Go/src/github.com/abiosoft/ishell/ishell.go:97 +0x39
main.main()
        /Volumes/Secondary/Boulot/Experiments/go/genious/gcreport/gcreport.go:77 +0x1c0
exit status 2`

**Comment by abiosoft** [comment]
Looks like a recent change to chzyer/readline is causing this.

**Comment by dr1ss** [comment]
Compiled it for linux and ran in on an ubuntu machine, same issue.

**Comment by abiosoft** [comment]
I noticed it works fine up until this commit https://github.com/chzyer/readline/commit/9f56defe66d6a0b145a2a2f19aa8c9a0d956b36a. Anything newer than that breaks ishell.

A quick workaround would be to vendor chzyer/readline.

**Comment by abiosoft** [comment]
I've found the issue and I've opened a PR https://github.com/chzyer/readline/pull/133. Hopefully it gets merged soon.

**Comment by dr1ss** [comment]
Thank you @abiosoft

**Comment by abiosoft** [comment]
https://github.com/chzyer/readline/pull/133 has been merged.
