### ISSUE TITLE
[Feature Request] Jumping to Commands

### ISSUE THREAD

**Issue by dr1ss** [abiosoft/ishell#67]
Hello guys,
I think it would be great to call (jump to) a command from another command.
Here is an usage example : 
- Command 1 = Lists log entries
- Command 2 = Read details about each log entry

The idea is calling the first command from the second one when the user is done reading the details about the log entry he selected.. So it basically returns him to the list of logs

**Comment by abiosoft** [comment]
You can always use functions to achieve similar purpose. i.e. command 1 and 2 can call same function to list log entries.

Feel free to reopen if you think otherwise.
