### ISSUE TITLE
Please tag a new release so this repo works better with dep

### ISSUE THREAD

**Issue by JelteF** [abiosoft/ishell#70]
The README says you are advised to upgrade to the the current master instead of v1. However, there's no v2 tag anywhere. `dep` installs the latest release by default, so it will still install v1.

**Comment by abiosoft** [comment]
you can actually use `gopkg.in/abiosoft/ishell.v2`. I don't want to tag a release yet as I still have some minor things to fix.

**Comment by abiosoft** [comment]
I have updated to readme accordingly.

Thanks.
