### ISSUE TITLE
Please expose context values through Shell object

### ISSUE THREAD

**Issue by matthijskooijman** [abiosoft/ishell#73]
I want to expose some values to all my shell commands, without resorting to global values, so the context values map seems an obvious way to do so.

However, right now, I can only access these values through a Context object, while executing a command, not from the outside. Duplicating Get/Set/Delete/Keys from context onto Shell is probably sufficient for this? Perhaps renaming to GetContextValue() etc to make it more explicit?

**Comment by abiosoft** [comment]
Done https://github.com/abiosoft/ishell/commit/42a9bbfa0017d7243b50b8f542076ef3d5e7da6c
The usage is same as with context. e.g. https://godoc.org/github.com/abiosoft/ishell#Shell.Set

**Comment by matthijskooijman** [comment]
Looks good, thanks for the quick response! :-)
