### ISSUE TITLE
Interactive startup / initialization

### ISSUE THREAD

**Issue by matthjes** [abiosoft/ishell#74]
Hi,

I could not find this function when I scanned the code: is it possible to have a kind of interactive startup, where, e.g., the user is asked to provide some information right after starting the application when some condition is met? For example, if a configuration parameter (path) is missing, then the user is asked right after startup to input this information, without the need to enter a command.

Example:
```
$user: go run myapp.go
This is myApp
Seems like this is the first start of the app. Please enter the directory to save the data:
>>>
```

**Comment by abiosoft** [comment]
You can use any of the `Action` methods on the shell instance before starting the shell to listen for commands.
e.g.
```go
func main(){
  shell := ishell.New()
  ...
  shell.Println("Seems like this is the first start of the app")
  shell.Print("Please enter the directory to save the data:")
  directory := shell.Readline()
  ...
  shell.Run()
}
```
Feel free to reopen the issue if that doesn't solve it for you.
