### ISSUE TITLE
Use github.com or gopkg.in import names?

### ISSUE THREAD

**Issue by matthijskooijman** [abiosoft/ishell#77]
The README mentions the gopkg.in names, but the examples use github.com. Which is recommended?

**Comment by abiosoft** [comment]
gopkg.in is meant to provide some stability. However, v2 is not fully done yet so gopkg.in/abiosoft/ishell.v2 is essential still same as the github.com/abiosoft/ishell.

Use github.com, I'll modify readme to address the confusion.

**Comment by matthijskooijman** [comment]
Thanks!

**Comment by matthijskooijman** [comment]
Just looked at switching to github, seems there's a v2 and a master branch. Perhaps you could also clarify the difference between those (especially if master is expected to be merged into v2 later or not)?

**Comment by abiosoft** [comment]
Yes, that is the plan. v2 is meant to be a more stable version of master.
