### ISSUE TITLE
Panic on completer if reverse search is used

### ISSUE THREAD

**Issue by omani** [abiosoft/ishell#85]
Hi abiosoft,

to reproduce this, do the following:
* enable history
* type in some command
```
$ exit
```

* now start shell again and do a reverse search with CTRL+R (like we used to do in bash)
* and type "ex" to let it find "exit"
```
CTRL+R ex
```
prompt will show:
```
$ exit
bck-i-search: ex 
```

so far so good. now since you've found the desired command, you could hit enter to execute it. but instead just try to complete the command by hitting tab.

panic at completer.go line 28.

you can try it with the main.go in examples. you will have to enable history for this to work though.

`shell.SetHistoryPath("/tmp/history")` so you can backsearch in the first place.

**Comment by omani** [comment]
you can try it with the main.go in examples. you will have to enable history for this to work though.

`shell.SetHistoryPath("/tmp/history")`

**Comment by abiosoft** [comment]
It never occurred to me that I can search history.

Thanks for reporting this. I will have a look when I have time, hopefully soon.

**Comment by omani** [comment]
I've found out that this bug is happening when you just move the cursor in front of a word and try to complete it. which is the case when doing above mentioned reverse search. so it is not dependent on a reverse search at all.

#86 fixes this.

**Comment by abiosoft** [comment]
Thanks @omani :)
