### ISSUE TITLE
*readline.Config has no field or method FuncFilterInputRune

### ISSUE THREAD

**Issue by Lobarr** [abiosoft/ishell#93]
```
vendor/gopkg.in/abiosoft/ishell.v2/ishell.go:446:6: conf.FuncFilterInputRune undefined (type *readline.Config has no field or method FuncFilterInputRune)
```
I keep getting the above error when I try to run the example you privided. How do I fix this error please?

**Comment by mangelajo** [comment]
Yeah, also experiencing this.

**Comment by abiosoft** [comment]
Closing this in favour of https://github.com/abiosoft/ishell/issues/92.
